# Form implementation generated from reading ui file 'python.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

from main import *
import os


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 675)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #The play button, this button will allow the code to be executed
        self.RunCode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RunCode.setGeometry(QtCore.QRect(350, 490, 51, 41))
        self.RunCode.setAutoFillBackground(True)
        self.RunCode.setText("")
        icon_path = r"C:\Users\willi\CSCI1620\Part2_Lab\download.png"
        if os.path.exists(icon_path):
            print("found")
            icon = QIcon(icon_path)
        else:
            print('fail')
            icon = QtGui.QIcon.fromTheme("folder")
        self.RunCode.setIcon(icon)
        self.RunCode.setIconSize(QtCore.QSize(40, 50))
        self.RunCode.setObjectName("RunCode")

        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 275, 550, 200))
        self.textEdit.setObjectName("textEdit")

        self.textLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.textLabel.setGeometry(QtCore.QRect(270, 10, 200, 30))
        self.textLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.textLabel.setText("Python Teaching App")
        self.textLabel.setObjectName("textLabel")

        self.treeView = QtWidgets.QTreeView(parent=self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(20, 60, 131, 401))
        self.treeView.setObjectName("treeView")

        self.problemButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.problemButton.setGeometry(QtCore.QRect(10, 600, 100, 30))
        self.problemButton.setText("Problem Mode")
        self.problemButton.setObjectName("problemButton")

        self.checkButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(120, 600, 100, 30))
        self.checkButton.setText("Check Solution")
        self.checkButton.setObjectName("checkButton")


        self.nextButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(660, 550, 75, 23))
        self.nextButton.setObjectName("nextButton")

        self.backButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 550, 75, 23))
        self.backButton.setObjectName("backButton")

        self.startLesson = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startLesson.setGeometry(QtCore.QRect(340, 550, 75, 23))
        self.startLesson.setObjectName("startLesson")

#ProgressBar was not programmed and cannot use it at this time.

        #self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        #self.progressBar.setGeometry(QtCore.QRect(480, 440, 118, 23))
        #self.progressBar.setProperty("value", 24)
        #self.progressBar.setObjectName("progressBar")

        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(160, 60, 550, 200))
        self.textBrowser.setObjectName("textBrowser")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setText(_translate("MainWindow", "Click Start to Begin the Lesson"))
        self.textLabel.setText(_translate("MainWindow", "Welcome to Python Teaching App\n Click Start Lesson"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.startLesson.setText(_translate("MainWindow", "Start Lesson"))
